#!/usr/bin/env python3
"""Render measured local stress results as a standalone HTML report."""
import json, html
from pathlib import Path
root=Path(__file__).resolve().parent.parent
r=json.loads((root/'artifacts/stress/results.json').read_text()); previous=json.loads((root/'artifacts/stress/exploratory-results.json').read_text()); phases=previous['phases']+r['phases']; total=sum(p['requests'] for p in phases); peak=max((p for p in phases if p['transport_errors']==0 and p['invalid_responses']==0),key=lambda p:p['rps']); soak=max(phases,key=lambda p:p['seconds'])
def f(n):return f'{n:,.1f}'
def chart():
    samples=[s for p in r['phases'] for s in p['samples']]+r.get('cooldown',[]);t0=samples[0]['t'];span=samples[-1]['t']-t0;maxrss=max(s['rss_mib'] for s in samples)*1.1
    pts=' '.join(f'{60+(s["t"]-t0)/span*880:.1f},{230-s["rss_mib"]/maxrss*190:.1f}' for s in samples)
    return f'<svg viewBox="0 0 1000 285" role="img" aria-label="Resident memory over elapsed test time"><path d="M60 30V230H940" fill="none" stroke="#aaa"/><polyline points="{pts}" fill="none" stroke="#15746b" stroke-width="2"/><text x="60" y="20">Server RSS (MiB), peak {f(max(s["rss_mib"] for s in samples))}</text><text x="60" y="255">0</text><text x="865" y="255">{span:.0f} seconds</text><text x="400" y="278">Elapsed test time (seconds)</text></svg>'
rows=''.join(f'<tr><td>{p["mode"]}{" · soak" if p is soak else ""}</td><td>{p["workers"]}</td><td>{p["seconds"]:.0f}s</td><td>{f(p["rps"])}</td><td>{f(p["p95_ms"])}</td><td>{f(p["p99_ms"])}</td><td>{f(p["server_cpu_core_percent"]/100)}</td><td>{f(p["peak_rss_mib"])}</td><td>{p["transport_errors"]} / {p["invalid_responses"]}</td></tr>' for i,p in enumerate(phases))
errors=sum(p['transport_errors']+p['invalid_responses'] for p in phases)
soak_samples=soak['samples']; a=sum(s['rss_mib'] for s in soak_samples[:10])/len(soak_samples[:10]);b=sum(s['rss_mib'] for s in soak_samples[-10:])/len(soak_samples[-10:])
page=f'''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>IP Info · Local stress test</title><style>body{{font:16px/1.6 system-ui,sans-serif;color:#182d35;background:#f6f7f5;max-width:1160px;margin:40px auto;padding:0 24px}}h1{{font-size:30px}}h2{{font-size:21px;margin-top:32px}}.lead{{font-size:21px;max-width:900px}}.metrics{{display:flex;gap:45px;flex-wrap:wrap;border-block:1px solid #c8d2d0;padding:22px 0}}.metrics strong{{display:block;font-size:28px;color:#15746b}}table{{border-collapse:collapse;width:100%;font-size:14px}}th,td{{padding:10px 8px;text-align:right;border-bottom:1px solid #d6dfdc}}th:first-child,td:first-child{{text-align:left}}small,.muted{{color:#53686e}}code,pre{{background:#e8eeeb;padding:3px 6px}}pre{{white-space:pre-wrap;padding:16px}}svg{{width:100%;background:white}}a{{color:#126f66}}.scroll{{overflow:auto}}</style>
<h1>IP Info: local stress test</h1><p class="muted">{html.escape(r['started'])} · Native macOS ARM64 release build · Real DB-IP database</p>
<p class="lead">{total:,} request attempts recorded with {errors} transport or response-validation failures. Peak error-free throughput was {peak['rps']:,.0f} requests/second. Errors occurred under extreme concurrency and connection churn; see the diagnostic detail below. These are local measurements, not a production capacity guarantee.</p>
<div class="metrics"><div><strong>{peak['rps']:,.0f}/s</strong>Peak error-free throughput</div><div><strong>{max(p['peak_rss_mib'] for p in phases):,.0f} MiB</strong>Peak sampled server RSS</div><div><strong>{errors}</strong>Transport / validation failures</div></div>
<h2>Throughput, latency and resources</h2><div class="scroll"><table><thead><tr><th>Workload</th><th>Connections</th><th>Time</th><th>Attempts/s</th><th>p95 ms</th><th>p99 ms</th><th>CPU cores¹</th><th>RSS MiB</th><th>Errors / invalid</th></tr></thead><tbody>{rows}</tbody></table></div>
<p><small>¹ CPU cores = process CPU time / elapsed wall time; 1.0 means one fully occupied core. CPU excludes the client. RSS sampled approximately once per second. Latency is rounded up to 0.1 ms histogram buckets and includes full response reading and JSON validation.</small></p>
<h2>Memory during sustained load</h2>{chart()}<p>The {soak['seconds']:.0f}-second soak sustained {soak['rps']:,.0f} requests/s. Mean RSS moved from {a:.1f} MiB in its first 10 samples to {b:.1f} MiB in its last 10 samples ({b-a:+.1f} MiB). After the 20-second cooldown, RSS was {r.get('cooldown',[r['baseline']])[-1]['rss_mib']:.1f} MiB. Memory-mapped database pages and allocator retention can keep RSS above the initial {r['baseline']['rss_mib']:.1f} MiB; RSS alone does not establish a heap leak.</p>
<h2>Transport error detail</h2><pre>{html.escape(json.dumps([{"mode":p["mode"],"workers":p["workers"],"errors":p["transport_errors"],"error_kinds":p.get("error_kinds", "not captured in initial run"),"readiness":{k:v for k,v in p["readiness"].items() if k != "database_date"}} for p in phases if p["transport_errors"]],indent=2))}</pre><h2>Test conditions</h2><pre>{html.escape(r['host'].strip())}</pre><ul><li>Private 1.3 GB DB-IP MMDB; native release server bound only to 127.0.0.1:18080. Client and server share the device. The report combines the initial concurrency sweep and a separate restarted process for the soak and diagnostic follow-ups. The memory chart shows only the follow-up process.</li><li>Varied workload uses deterministic, changing public IPv4 and IPv6 addresses. Hot workload repeats 8.8.8.8. Mixed workload combines lookups, HTML pages and expected 400 responses. Churn opens a new connection per request.</li><li>Each worker has one request in flight. This is a closed-loop saturation test, not a fixed-arrival-rate capacity test. Higher concurrency can increase queueing latency.</li><li>Checks cover response status and, for successful lookups, parsed IP identity. Expected missing records (404) and intentional invalid input (400) are not server failures.</li><li>All seven functional tests passed, including the two opt-in tests against the private database. Readiness probe results are recorded in the raw data; connection churn may exhaust client ports and prevent probes. Server exit: {r.get('server_exit','pending')}.</li></ul>
<h2>Assessment</h2><p>High keep-alive throughput passed at moderate concurrency. At 512 connections, connection resets reproduced; this is an overload limitation. The two-minute soak had no errors, but RSS continued to rise as varied lookups touched the memory-mapped database, so this test does not establish a memory plateau or exclude a leak. Churn errors caused by exhausted local source ports are a load-generator/host limit and cannot be treated as server capacity.</p><h2>What these results do and do not establish</h2><p>The measured workloads exercise high local throughput and short sustained resource behavior. They do not establish a maximum production RPS or rule out long-running leaks. No TLS, remote network, container memory/CPU limits, ingress, HTTP/2 load, multi-hour soak, or connection-exhaustion test was included. Host cache may already be warm.</p><p>Code inspection also shows no global accepted-connection cap in the server. Per-connection HTTP/2 stream and header limits exist, but total concurrent connections still need bounding at ingress or in the server for public overload protection.</p>
<h2>Reproduce locally</h2><pre>cargo build --release --locked --offline
cargo build --release --example stress --locked --offline
cargo test --locked --offline
cargo test --locked --offline -- --ignored
python3 scripts/stress_test.py
python3 scripts/render_stress_report.py</pre><p>The runner starts its own server, samples resources, performs the scenarios, and stops the server. Port 18080 must be free. Raw data: <a href="../artifacts/stress/results.json">results.json</a>. Load generator: <a href="../examples/stress.rs">stress.rs</a>. Runner: <a href="../scripts/stress_test.py">stress_test.py</a>.</p></html>'''
(root/'docs/stress-test.html').write_text(page)
print(root/'docs/stress-test.html')
