#!/usr/bin/env python3
"""Render the measured local benchmark and verification evidence as standalone HTML."""
import html, json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]

def main():
    benchmark=json.loads((ROOT/'artifacts/benchmark.json').read_text())
    browser=json.loads((ROOT/'artifacts/browser-results.json').read_text())
    stats=browser['stats']
    if stats.get('unexpected') or stats.get('flaky') or stats.get('skipped') or stats.get('expected')!=6:
        raise SystemExit('Expected six clean browser checks before recording success.')
    rows=''
    for r in benchmark['passes']:
        m=r['resource_after']; label='First varied-IP pass' if r['name']=='first_pass' else 'Same IPs, warm repeat'
        rows+=f'<tr><th>{label}</th><td>{r["requests_per_second"]:,.1f}</td><td>{r["p50_ms"]}</td><td>{r["p95_ms"]}</td><td>{r["p99_ms"]}</td><td>{r["cpu_core_percent"]}%</td><td>{m["memory.current"]/1048576:.1f}</td></tr>'
    report=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>IP Info — Local validation</title><style>
    :root{{color-scheme:dark;font:16px/1.65 system-ui,sans-serif;background:#080c16;color:#e8f0ff}}body{{margin:0}}main{{max-width:1050px;margin:auto;padding:50px 25px}}h1{{font-size:2.7rem;line-height:1.1;letter-spacing:-.04em}}h2{{margin-top:38px}}a{{color:#83b2ff}}p,li{{color:#b2c1d8}}.badge{{color:#89e4ba;font-size:.9rem}}.cards{{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin:30px 0}}.card{{background:#111b2c;border:1px solid #293953;padding:20px;border-radius:12px}}.card strong{{display:block;font-size:1.7rem}}.card span{{color:#9bb1d1;font-size:.85rem}}table{{border-collapse:collapse;width:100%;font-size:.85rem}}th,td{{border-bottom:1px solid #2a3850;text-align:left;padding:12px 9px}}.table{{overflow:auto}}code{{color:#bdd6ff;overflow-wrap:anywhere}}.note{{border-left:3px solid #2b7fff;padding:15px 20px;background:#101d33}}details{{margin-top:25px}}pre{{font-size:.8rem;overflow:auto;background:#0e192a;padding:20px}}@media(max-width:650px){{.cards{{grid-template-columns:1fr}}h1{{font-size:2.1rem}}}}
    </style></head><body><main><span class="badge">LOCAL VALIDATION · SEPTEMBER 29, 2026</span><h1>IP Info is built and locally verified.</h1><p>Rust API, DB-IP data, standalone website, agent documentation, consent-controlled analytics, and a Bunny-compatible container.</p>
    <div class="cards"><div class="card"><strong>7 Rust tests</strong><span>Unit and API integration checks passed</span></div><div class="card"><strong>6 browser checks</strong><span>Desktop, mobile, offline and consent passed</span></div><div class="card"><strong>40,000 lookups</strong><span>All returned HTTP 200 in the measured run</span></div></div>
    <h2>What was verified</h2><ul><li>Real September 14 MMDB copied locally; SHA-256 matches the source manifest. The 1.3 GB file is ignored by Git and is not served publicly.</li><li>Exact documented example match, nullable fields, IPv6, IPv4-mapped IPv6, input errors, CORS, no-store responses and forged forwarding headers.</li><li>Independent Python MMDB comparisons passed for five IPv4/IPv6 addresses.</li><li>Formatting and Clippy with warnings denied passed. OpenAPI/field references, sitemap, metadata, structured JSON and internal links passed validation.</li><li>Desktop/mobile appearance visually inspected, including 320 px and 390 px widths. Keyboard, copy controls, no-JavaScript form submission and direct-file documentation navigation passed.</li><li>Analytics tests intercepted Google requests locally: no pre-consent traffic, rejection respected, allowed events sanitized, withdrawal removes the loader/cookies and reloads safely. No events were sent to a real GA4 property.</li><li>Read-only non-root container, liveness/readiness and corrupted-database behavior tested. Invalid MMDB returned readiness/lookup 503 while liveness remained 200. Graceful shutdown exited 0 without an OOM.</li></ul>
    <h2>Container compatibility</h2><p>The final Linux amd64 image passed local API/page smoke checks under local emulation. Image ID: <code>sha256:1115aa4d776a3eb94c237c99a331954961c7a009eba92269ba42b1a0ba5ce447</code>. Its size is 1,427,216,688 bytes including the licensed database. It is available locally as <code>ip-info:amd64</code>; no image was pushed to a registry.</p><h2>Measured resource use</h2><p>Native Linux arm64 container on the local Mac’s Docker engine, capped at 1 CPU and 2 GiB. A Python client issued 20,000 distinct mixed IPv4/IPv6 lookups per pass using 16 workers and persistent HTTP connections.</p><div class="table"><table><thead><tr><th>Workload</th><th>Requests/s</th><th>p50 ms</th><th>p95 ms</th><th>p99 ms</th><th>CPU core use</th><th>Memory MiB</th></tr></thead><tbody>{rows}</tbody></table></div>
    <p>Peak cgroup memory was {benchmark['passes'][-1]['resource_after']['memory.peak']/1048576:.1f} MiB. After the warm run, anonymous memory was {benchmark['passes'][-1]['resource_after']['memory.stat']['anon']/1048576:.1f} MiB and file-backed memory was {benchmark['passes'][-1]['resource_after']['memory.stat']['file']/1048576:.1f} MiB. The native release binary was approximately 3.7 MB; the private image is approximately 1.45 GB because it contains the MMDB.</p>
    <div class="note">These are local measurements, not a throughput guarantee or production sizing proof. The first pass was not guaranteed OS-cache-cold. The load generator, container networking and other local work affect latency. Use 2 GiB as the initial deployment budget and measure representative traffic before reducing it.</div>
    <h2>Launch configuration still needed</h2><ul><li>Private registry upload and live Bunny deployment, domain/DNS and TLS configuration.</li><li>Verify Bunny’s actual client-IP ingress header and peer trust boundary, HTTP without redirects and API cache bypass from two real networks.</li><li>GA4 Measurement ID plus property settings: disable Enhanced Measurement/advertising features and verify two-month event retention. Analytics remains disabled without an ID.</li><li>Full registered operator details and actual hosting-log retention before final legal publication. The verified public contact is hi@shifter.io.</li><li>Search Console verification and sitemap submission. SITE_INDEXABLE remains false until production checks are complete.</li><li>Daily database updates remain a separate follow-up, as requested.</li></ul>
    <p><a href="operations.html">Build and deployment guide</a> · <a href="../web/index.html">Standalone website</a> · <a href="../web/docs.html">API reference</a> · <a href="../web/openapi.json">OpenAPI</a></p>
    <details><summary>Embedded benchmark evidence</summary><pre>{html.escape(json.dumps(benchmark,indent=2))}</pre></details></main></body></html>'''
    (ROOT/'docs/validation.html').write_text(report)
    print('Wrote docs/validation.html')
if __name__=='__main__':main()
